### ISSUE TITLE
Minimum version of macOS

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfaviz#56]
```
Project WARNING: Qt requires at least version 10.13 of the platform SDK, you're using 10.12. Please upgrade.
Sorry, "uic" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.
```
Please add to the documentation that the minimum version of macOS is 10.12.

I'm on my work computer, which is outdated. I'm looking forward to trying out GfaViz when I get home to my laptop!

**Comment by ggonnella** [comment]
Thank you for the feedback. Added this to the manual.
