### ISSUE TITLE
Please tag a stable release version 1.0.0

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfaviz#57]
Thanks!

**Comment by druvus** [comment]
It would be nice to have a tagged release corresponding to the manuscript version (or later).

**Comment by ggonnella** [comment]
We tagged now a version 0.9. After implementing the request of @sjackman to change the executable name and to have a make install target, as well as a fast check for other issues which can be easily fixed, I will release v1.0.0 (due time: next week).

**Comment by ggonnella** [comment]
Stable version was released, v1.0.0
