### ISSUE TITLE
Please defork ggonnella/gfaviz

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfaviz#58]
> ggonnella/gfaviz
forked from niehus/gfaviz

Which is the canonical repository, ggonnella/gfaviz or niehus/gfaviz? If it's ggonnella, could you please delete the repo `ggonnella/gfaviz` and then transfer ownership of the repo `niehus/gfaviz` to `ggonnella`.

**Comment by ggonnella** [comment]
Thank you for the suggestion. We transfered ownership. The main repository is now ggonnella/gfaviz.
