### ISSUE TITLE
make install has no effect

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfaviz#59]
```console
$ qmake PREFIX=$HOME
$ make
…
$ make install
make: Nothing to be done for `install'.
```
This is on macOS. I haven't yet tested Linux.
Could `make install` install the executable in the `bin` directory of the specified prefix?

**Comment by sjackman** [comment]
Also could the executable be renamed from `viz.x` to `gfaviz`?

**Comment by ggonnella** [comment]
Both issues were now fixed.
