### ISSUE TITLE
gfaviz incompatible with TwoPaCo graph

### ISSUE THREAD

**Issue by alexweisberg** [ggonnella/gfaviz#61]
Hi, This software looks great and I would love to use it for analyzing some graphs. I have a gfa graph that I assembled using TwoPaCo (twopaco -> graphdump). I can open this graph in Bandage, however when I try to open it in gfaviz I get the following error: 
>Error opening file "/Volumes/Media Drive/Research/graphs/mygraph.gfa": Line 19: Not enough columns found.

When I export in gfa2 format and try to open that, I get a different error:
>Error opening file "/Volumes/Media Drive/Research/graphs/mygraph.gfa2": Line 6, column 3: No orientation found in reference '0'.

I've attached the graph files specified in the error messages. Thanks!

[Archive.zip](https://github.com/ggonnella/gfaviz/files/2867220/Archive.zip)

**Comment by ggonnella** [comment]
Thank you for reporting this. I will have a look at it asap and find a solution.

Best regards,
Giorgio

Am 15. Februar 2019 00:56:59 MEZ schrieb Alexandra Weisberg <notifications@github.com>:
>Hi, This software looks great and I would love to use it for analyzing
>some graphs. I have a gfa graph that I assembled using TwoPaCo (twopaco
>-> graphdump). I can open this graph in Bandage, however when I try to
>open it in gfaviz I get the following error: 
>>Error opening file "/Volumes/Media Drive/Research/graphs/mygraph.gfa":
>Line 19: Not enough columns found.
>
>When I export in gfa2 format and try to open that, I get a different
>error:
>>Error opening file "/Volumes/Media
>Drive/Research/graphs/mygraph.gfa2": Line 6, column 3: No orientation
>found in reference '0'.
>
>I've attached the graph files specified in the error messages. Thanks!
>
>[Archive.zip](https://github.com/ggonnella/gfaviz/files/2867220/Archive.zip)
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ggonnella/gfaviz/issues/61

-- 
Dr. Giorgio Gonnella

**Comment by ggonnella** [comment]
I had a look to the GFA graph output by TwoPaCo. Unfortunately the output only resembles GFA but is not GFA, meaning that it does not respect any GFA specification at all.

These are the issues I found using gfapy-validate (tool available in the GfaPy package) in the GFA1 file:
- (1) Containment lines are wrongly formatted, i.e. they miss the last field, which describes the alignment. This field can, according to GFA, be without content, but in that case it must be present and contain an asterisk symbol *.
- (2) Links must be unique. They are not, some link lines are repeated multiple times.
- (3) Paths have an ID, which is the same namespace as the Segment IDs. This is not respected, i.e. there are paths in the file, which are called exactly as the segments.
- (4) Paths must contain at least two segments. But there are path lines in the file, which have a single segment in them.

I was able to produce a valid GFA by doing the following, which fixes the C lines, removes duplicated lines and finally removes the P lines completely (I hope you did not want to visualize mainly them).

```
# add missing field to the C lines:
sed 's/^C\(.*\)/C\1\t*/' mygraph.gfa > mygraph.fix1.gfa
# remove duplicated lines:
sort -u mygraph.fix1.gfa > mygraph.fix2.gfa
# remove the paths, as they do not respect the specification:
grep -v "^P" mygraph.fix2.gfa > mygraph.fix3.gfa
```

I was able to visualize mygraph.fix3.gfa with GfaViz.

**Comment by ggonnella** [comment]
The GFA2 file is invalid as well. The problem here are the E lines. They miss the second field, which contain the optional ID of the Edge. Again, if missing, they must contain a "*", but they do not.

 So I added the field using the following:
```
sed 's/^E/E\t*/' mygraph.gfa2 > mygraph.fix1.gfa2
```
And I was able to visualize the file correctly.

I think you should then rather use the GFA2 instead of the GFA1, as here it was not necessary to delete any data (paths) as in the GFA1 file.

**Comment by ggonnella** [comment]
@alexweisberg If you could also report the bugs in the GFA output to TwoPaCo, this is probably better, than if I do it, as I do not know e.g. which version you used etc. You can cross-link there to this issue.

**Comment by alexweisberg** [comment]
Thank you for looking into this! I will let the TwoPaCo group know too.
